"""Write the packaged Conductor skill into a project for agents to discover.

The skill teaches an agent how to find and connect to a running DerZug; the
canvas-driving briefing itself lives behind the ``get_derzug_rules`` tool so
it can never drift from the running app. Stdlib-only, no ``mcp`` dependency.
"""

from __future__ import annotations

import logging
from importlib import resources
from pathlib import Path

from derzug.conductor.constants import SERVER_NAME

log = logging.getLogger(__name__)

#: Marks a skill file as ours to overwrite; a user who removes it owns the file.
GENERATED_MARKER = "<!-- generated by derzug; regenerated on Conductor start -->"

#: Per-client project skill locations (Claude Code and the open agents standard).
SKILL_DIRS = (
    Path(".claude") / "skills" / SERVER_NAME,
    Path(".agents") / "skills" / SERVER_NAME,
)


def skill_text() -> str:
    """Return the packaged SKILL.md content."""
    asset = resources.files("derzug.conductor") / "skill_assets" / "SKILL.md"
    return asset.read_text(encoding="utf-8")


def write_skill_files(project_dir: str | Path) -> list[Path]:
    """Write the skill into each client's skill dir under ``project_dir``.

    An existing file is overwritten only while it still carries the generated
    marker; a copy that was modified — or that cannot even be read back —
    belongs to the user and is left alone (logged), going stale by design.
    Returns the paths written.
    """
    text = skill_text()
    written = []
    for skill_dir in SKILL_DIRS:
        path = Path(project_dir) / skill_dir / "SKILL.md"
        if path.exists():
            try:
                existing = path.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                log.info("Leaving unreadable skill file untouched: %s", path)
                continue
            if GENERATED_MARKER not in existing:
                log.info("Leaving user-modified skill file untouched: %s", path)
                continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written


__all__ = ("GENERATED_MARKER", "SKILL_DIRS", "skill_text", "write_skill_files")
