"""Qt form for editing autogenerated DASCore example parameters.

The policy for *what* the parameters are lives in
:mod:`derzug.utils.example_parameters`, which stays Qt-free so the Spool node
can build its own call kwargs headlessly; this module is only its editor.
"""

from __future__ import annotations

import numpy as np
from AnyQt.QtWidgets import (
    QCheckBox,
    QDialog,
    QDialogButtonBox,
    QDoubleSpinBox,
    QFormLayout,
    QLabel,
    QLineEdit,
    QPushButton,
    QSpinBox,
    QVBoxLayout,
    QWidget,
)

from derzug.utils.display import format_display
from derzug.utils.example_parameters import (
    ExampleParameterSpec,
    parse_example_parameter_text,
)

__all__ = ("ExampleParametersDialog",)


def _format_parameter_text(value: object) -> str:
    """Return the string shown inside a text-backed parameter editor."""
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    if isinstance(value, (np.timedelta64 | np.datetime64)):
        return format_display(value)
    return repr(value)


class ExampleParametersDialog(QDialog):
    """Modal dialog auto-generated from one example function signature."""

    def __init__(
        self,
        *,
        example_name: str,
        specs: tuple[ExampleParameterSpec, ...],
        saved_values: dict[str, object] | None = None,
        parent=None,
    ) -> None:
        super().__init__(parent)
        self._example_name = example_name
        self._specs = specs
        self._saved_values = saved_values or {}
        self._inputs: dict[str, QWidget] = {}
        self._parsed_values: dict[str, object] | None = None
        self.setWindowTitle(f"Example Parameters: {example_name}")
        self.setModal(True)
        self.resize(420, 320)

        layout = QVBoxLayout(self)
        intro = QLabel(
            (
                "These controls are generated from the selected example "
                "function signature."
            ),
            self,
        )
        intro.setWordWrap(True)
        layout.addWidget(intro)

        if not specs:
            empty = QLabel("This example exposes no configurable parameters.", self)
            empty.setWordWrap(True)
            layout.addWidget(empty)
        else:
            form_host = QWidget(self)
            form = QFormLayout(form_host)
            form.setContentsMargins(0, 0, 0, 0)
            form.setSpacing(8)
            for spec in specs:
                widget = self._create_editor(spec)
                self._inputs[spec.name] = widget
                form.addRow(f"{spec.name}:", widget)
            layout.addWidget(form_host, 1)

        self._error_label = QLabel("", self)
        self._error_label.setWordWrap(True)
        self._error_label.setStyleSheet("color: #b91c1c;")
        self._error_label.hide()
        layout.addWidget(self._error_label)

        buttons = QDialogButtonBox(QDialogButtonBox.StandardButton.Cancel, self)
        self._reset_button = QPushButton("Reset to Defaults", self)
        buttons.addButton(self._reset_button, QDialogButtonBox.ButtonRole.ResetRole)
        self._apply_button = QPushButton("Apply", self)
        buttons.addButton(self._apply_button, QDialogButtonBox.ButtonRole.AcceptRole)
        buttons.rejected.connect(self.reject)
        self._reset_button.clicked.connect(self._reset_to_defaults)
        self._apply_button.clicked.connect(self._apply)
        if not specs:
            self._apply_button.setText("Close")
            self._apply_button.clicked.disconnect()
            self._apply_button.clicked.connect(self.accept)
            self._reset_button.hide()
        layout.addWidget(buttons)

    @property
    def parsed_values(self) -> dict[str, object]:
        """Return the parsed values after a successful Apply/OK."""
        return dict(self._parsed_values or {})

    def _create_editor(self, spec: ExampleParameterSpec) -> QWidget:
        """Create one editor widget from a parameter spec."""
        current_value = self._saved_values.get(spec.name, spec.default)
        if spec.kind == "bool":
            checkbox = QCheckBox(self)
            checkbox.setChecked(bool(current_value))
            return checkbox
        if spec.kind == "int":
            spin = QSpinBox(self)
            spin.setRange(-(2**31), 2**31 - 1)
            spin.setValue(int(current_value if current_value is not None else 0))
            return spin
        if spec.kind == "float":
            spin = QDoubleSpinBox(self)
            spin.setDecimals(6)
            spin.setRange(-1e12, 1e12)
            spin.setValue(float(current_value if current_value is not None else 0.0))
            return spin
        line_edit = QLineEdit(self)
        line_edit.setText(_format_parameter_text(current_value))
        line_edit.setPlaceholderText(_format_parameter_text(spec.default))
        return line_edit

    def _reset_to_defaults(self) -> None:
        """Reset all editor widgets to their signature defaults."""
        for spec in self._specs:
            widget = self._inputs[spec.name]
            value = spec.default
            if isinstance(widget, QCheckBox):
                widget.setChecked(bool(value))
            elif isinstance(widget, QSpinBox):
                widget.setValue(int(value if value is not None else 0))
            elif isinstance(widget, QDoubleSpinBox):
                widget.setValue(float(value if value is not None else 0.0))
            elif isinstance(widget, QLineEdit):
                widget.setText(_format_parameter_text(value))
        self._clear_error()

    def _apply(self) -> None:
        """Parse the form values and accept the dialog when valid."""
        try:
            parsed = self._parse_values()
        except ValueError as exc:
            self._error_label.setText(str(exc))
            self._error_label.show()
            return
        self._parsed_values = parsed
        self._clear_error()
        self.accept()

    def _clear_error(self) -> None:
        """Hide the inline validation error label."""
        self._error_label.hide()
        self._error_label.clear()

    def _parse_values(self) -> dict[str, object]:
        """Return parsed Python values from the current editor states."""
        output: dict[str, object] = {}
        for spec in self._specs:
            widget = self._inputs[spec.name]
            if isinstance(widget, QCheckBox):
                output[spec.name] = widget.isChecked()
                continue
            if isinstance(widget, QSpinBox):
                output[spec.name] = int(widget.value())
                continue
            if isinstance(widget, QDoubleSpinBox):
                output[spec.name] = float(widget.value())
                continue
            if isinstance(widget, QLineEdit):
                output[spec.name] = parse_example_parameter_text(
                    widget.text(),
                    default=spec.default,
                    annotation=spec.annotation,
                    optional=spec.optional,
                )
        return output
